### ISSUE TITLE
Might have to pip random if running in VS code ( Alien Game)

### ISSUE THREAD

**Issue by Stari-Div** [CursedGhoul/Alien-Game#2]
--     For alien game ( https://github.com/CursedGhoul/Alien-Game ) if you run it in VS code you might have to run ( pip install random ) in the console, it would be nice to put that in the read me
     @Stari-Div

**Comment by CursedGhoul** [comment]
There is in `import random` at the top to import it

**Comment by CursedGhoul** [comment]
Closed it under wrong thing
